/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DebugComponentsRouteImport } from './routes/debug/components'
import { Route as AuthPathRouteImport } from './routes/auth/$path'
import { Route as ProtectedConsoleRouteImport } from './routes/_protected/console'
import { Route as ProtectedConsoleIndexRouteImport } from './routes/_protected/console/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as ProtectedConsoleSettingsRouteImport } from './routes/_protected/console/settings'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin/users'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin/settings'
import { Route as AdminAdminAuthRouteImport } from './routes/_admin/admin/auth'
import { Route as AdminAdminAuthSplatRouteImport } from './routes/_admin/admin/auth/$'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugComponentsRoute = DebugComponentsRouteImport.update({
  id: '/debug/components',
  path: '/debug/components',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathRoute = AuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedConsoleRoute = ProtectedConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedConsoleIndexRoute = ProtectedConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedConsoleRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const ProtectedConsoleSettingsRoute =
  ProtectedConsoleSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedConsoleRoute,
  } as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAuthRoute = AdminAdminAuthRouteImport.update({
  id: '/admin/auth',
  path: '/admin/auth',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAuthSplatRoute = AdminAdminAuthSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminAdminAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ProtectedConsoleRouteWithChildren
  '/auth/$path': typeof AuthPathRoute
  '/debug/components': typeof DebugComponentsRoute
  '/admin/auth': typeof AdminAdminAuthRouteWithChildren
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/console/settings': typeof ProtectedConsoleSettingsRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/console/': typeof ProtectedConsoleIndexRoute
  '/admin/auth/$': typeof AdminAdminAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/$path': typeof AuthPathRoute
  '/debug/components': typeof DebugComponentsRoute
  '/admin/auth': typeof AdminAdminAuthRouteWithChildren
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/console/settings': typeof ProtectedConsoleSettingsRoute
  '/admin': typeof AdminAdminIndexRoute
  '/console': typeof ProtectedConsoleIndexRoute
  '/admin/auth/$': typeof AdminAdminAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/console': typeof ProtectedConsoleRouteWithChildren
  '/auth/$path': typeof AuthPathRoute
  '/debug/components': typeof DebugComponentsRoute
  '/_admin/admin/auth': typeof AdminAdminAuthRouteWithChildren
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_protected/console/settings': typeof ProtectedConsoleSettingsRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_protected/console/': typeof ProtectedConsoleIndexRoute
  '/_admin/admin/auth/$': typeof AdminAdminAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/auth/$path'
    | '/debug/components'
    | '/admin/auth'
    | '/admin/settings'
    | '/admin/users'
    | '/console/settings'
    | '/admin/'
    | '/console/'
    | '/admin/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/$path'
    | '/debug/components'
    | '/admin/auth'
    | '/admin/settings'
    | '/admin/users'
    | '/console/settings'
    | '/admin'
    | '/console'
    | '/admin/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_protected'
    | '/_protected/console'
    | '/auth/$path'
    | '/debug/components'
    | '/_admin/admin/auth'
    | '/_admin/admin/settings'
    | '/_admin/admin/users'
    | '/_protected/console/settings'
    | '/_admin/admin/'
    | '/_protected/console/'
    | '/_admin/admin/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthPathRoute: typeof AuthPathRoute
  DebugComponentsRoute: typeof DebugComponentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/components': {
      id: '/debug/components'
      path: '/debug/components'
      fullPath: '/debug/components'
      preLoaderRoute: typeof DebugComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$path': {
      id: '/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/console': {
      id: '/_protected/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ProtectedConsoleRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/console/': {
      id: '/_protected/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ProtectedConsoleIndexRouteImport
      parentRoute: typeof ProtectedConsoleRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_protected/console/settings': {
      id: '/_protected/console/settings'
      path: '/settings'
      fullPath: '/console/settings'
      preLoaderRoute: typeof ProtectedConsoleSettingsRouteImport
      parentRoute: typeof ProtectedConsoleRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/auth': {
      id: '/_admin/admin/auth'
      path: '/admin/auth'
      fullPath: '/admin/auth'
      preLoaderRoute: typeof AdminAdminAuthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/auth/$': {
      id: '/_admin/admin/auth/$'
      path: '/$'
      fullPath: '/admin/auth/$'
      preLoaderRoute: typeof AdminAdminAuthSplatRouteImport
      parentRoute: typeof AdminAdminAuthRoute
    }
  }
}

interface AdminAdminAuthRouteChildren {
  AdminAdminAuthSplatRoute: typeof AdminAdminAuthSplatRoute
}

const AdminAdminAuthRouteChildren: AdminAdminAuthRouteChildren = {
  AdminAdminAuthSplatRoute: AdminAdminAuthSplatRoute,
}

const AdminAdminAuthRouteWithChildren = AdminAdminAuthRoute._addFileChildren(
  AdminAdminAuthRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminAuthRoute: typeof AdminAdminAuthRouteWithChildren
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAuthRoute: AdminAdminAuthRouteWithChildren,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProtectedConsoleRouteChildren {
  ProtectedConsoleSettingsRoute: typeof ProtectedConsoleSettingsRoute
  ProtectedConsoleIndexRoute: typeof ProtectedConsoleIndexRoute
}

const ProtectedConsoleRouteChildren: ProtectedConsoleRouteChildren = {
  ProtectedConsoleSettingsRoute: ProtectedConsoleSettingsRoute,
  ProtectedConsoleIndexRoute: ProtectedConsoleIndexRoute,
}

const ProtectedConsoleRouteWithChildren =
  ProtectedConsoleRoute._addFileChildren(ProtectedConsoleRouteChildren)

interface ProtectedRouteChildren {
  ProtectedConsoleRoute: typeof ProtectedConsoleRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedConsoleRoute: ProtectedConsoleRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthPathRoute: AuthPathRoute,
  DebugComponentsRoute: DebugComponentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
